-- =======================================================================
-- DATABASE CREATION SCRIPT: offline_exam_system
-- =======================================================================

-- Create schema/user for Oracle (optional depending on setup)
CREATE USER offline_exam_system IDENTIFIED BY exam123;
GRANT CONNECT, RESOURCE TO offline_exam_system;
ALTER USER offline_exam_system DEFAULT ROLE ALL;

-- Switch to schema
ALTER SESSION SET CURRENT_SCHEMA = offline_exam_system;

-- =======================================================================
-- TABLES, SEQUENCES, AND TRIGGERS
-- =======================================================================

-- USERS TABLE
CREATE TABLE USERS (
    user_id VARCHAR2(20) PRIMARY KEY,
    username VARCHAR2(50) UNIQUE NOT NULL,
    password VARCHAR2(255) NOT NULL,
    role VARCHAR2(20) CHECK (role IN ('ADMIN','TEACHER','STUDENT')),
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP
);
CREATE SEQUENCE user_seq START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER trg_user_id
BEFORE INSERT ON USERS
FOR EACH ROW
BEGIN
    IF :NEW.role = 'ADMIN' THEN
        :NEW.user_id := 'ADM-' || TO_CHAR(user_seq.NEXTVAL, 'FM0000');
    ELSIF :NEW.role = 'TEACHER' THEN
        :NEW.user_id := 'INS-' || TO_CHAR(user_seq.NEXTVAL, 'FM0000');
    ELSE
        :NEW.user_id := '24RP0-' || TO_CHAR(user_seq.NEXTVAL, 'FM0000');
    END IF;
END;
/

-- COURSES TABLE
CREATE TABLE COURSES (
    course_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_name VARCHAR2(100) NOT NULL,
    description CLOB,
    created_by VARCHAR2(20),
    FOREIGN KEY (created_by) REFERENCES USERS(user_id)
);

-- ENROLLMENTS TABLE (for student enrollments)
CREATE TABLE ENROLLMENTS (
    enrollment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id VARCHAR2(20) NOT NULL,
    course_id NUMBER NOT NULL,
    status VARCHAR2(20) CHECK (status IN ('PENDING','APPROVED','REJECTED')) DEFAULT 'PENDING',
    request_date TIMESTAMP DEFAULT SYSTIMESTAMP,
    approved_by VARCHAR2(20),
    FOREIGN KEY (student_id) REFERENCES USERS(user_id),
    FOREIGN KEY (approved_by) REFERENCES USERS(user_id),
    FOREIGN KEY (course_id) REFERENCES COURSES(course_id)
);

-- EXAMS TABLE
CREATE TABLE EXAMS (
    exam_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id NUMBER,
    exam_name VARCHAR2(100) NOT NULL,
    exam_date DATE,
    duration_minutes NUMBER,
    created_by VARCHAR2(20),
    FOREIGN KEY (course_id) REFERENCES COURSES(course_id),
    FOREIGN KEY (created_by) REFERENCES USERS(user_id)
);
-- QUESTIONS TABLE
CREATE TABLE QUESTIONS (
    question_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_id NUMBER,
    question_text CLOB NOT NULL,
    question_type VARCHAR2(20) CHECK (question_type IN ('MCQ','ESSAY','TRUE_FALSE')),
    marks NUMBER(5,2),
    FOREIGN KEY (exam_id) REFERENCES EXAMS(exam_id)
);

-- OPTIONS TABLE (for MCQs)
CREATE TABLE OPTIONS (
    option_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id NUMBER,
    option_text VARCHAR2(255),
    is_correct CHAR(1) CHECK (is_correct IN ('Y','N')),
    FOREIGN KEY (question_id) REFERENCES QUESTIONS(question_id)
);

-- RESULTS TABLE
CREATE TABLE RESULTS (
    result_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id VARCHAR2(20),
    exam_id NUMBER,
    score NUMBER(5,2),
    graded_by VARCHAR2(20),
    date_taken TIMESTAMP DEFAULT SYSTIMESTAMP,
    FOREIGN KEY (student_id) REFERENCES USERS(user_id),
    FOREIGN KEY (exam_id) REFERENCES EXAMS(exam_id),
    FOREIGN KEY (graded_by) REFERENCES USERS(user_id)
);

-- USER LOGS TABLE
CREATE TABLE USER_LOGS (
    log_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR2(20),
    action VARCHAR2(100),
    log_time TIMESTAMP DEFAULT SYSTIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES USERS(user_id)
);


